import type {
  CombatantType,
  CreatureTemplate,
  EncounterCombatant,
} from "./types";

export const typeStyles: Record<
  CombatantType,
  { label: string; accent: string; badge: string; dot: string }
> = {
  pc: {
    label: "PC",
    accent: "border-sky-500",
    badge: "bg-sky-100 text-sky-900 border-sky-300",
    dot: "bg-sky-500",
  },
  ally: {
    label: "Ally",
    accent: "border-emerald-500",
    badge: "bg-emerald-100 text-emerald-900 border-emerald-300",
    dot: "bg-emerald-500",
  },
  enemy: {
    label: "Enemy",
    accent: "border-rose-500",
    badge: "bg-rose-100 text-rose-900 border-rose-300",
    dot: "bg-rose-500",
  },
  boss: {
    label: "Boss",
    accent: "border-amber-500",
    badge: "bg-amber-100 text-amber-950 border-amber-300",
    dot: "bg-amber-500",
  },
  summon: {
    label: "Summon",
    accent: "border-violet-500",
    badge: "bg-violet-100 text-violet-900 border-violet-300",
    dot: "bg-violet-500",
  },
  neutral: {
    label: "Neutral",
    accent: "border-zinc-400",
    badge: "bg-zinc-100 text-zinc-800 border-zinc-300",
    dot: "bg-zinc-500",
  },
};

const commonScores = {
  str: 10,
  dex: 10,
  con: 10,
  int: 10,
  wis: 10,
  cha: 10,
};

export const sampleCreatureTemplates: CreatureTemplate[] = [
  {
    id: "pc-aria",
    name: "Aria Vale",
    type: "pc",
    size: "Medium",
    armorClass: 17,
    maxHp: 42,
    speed: "30 ft.",
    initiativeBonus: 2,
    abilityScores: { ...commonScores, str: 15, con: 14, cha: 13 },
    savingThrows: ["Str +5", "Con +4"],
    skills: ["Athletics +5", "Insight +3"],
    senses: "passive Perception 11",
    languages: "Common, Dwarvish",
    traits: [{ name: "Shield Line", description: "Adjacent allies gain cover while Aria is not down." }],
    actions: [{ name: "Longblade", description: "+5 to hit, 1d8+3 slashing damage." }],
    notes: "Front-line defender with reliable protection.",
    tags: ["player", "defender"],
    color: "Blue",
    autoRollEligible: false,
  },
  {
    id: "pc-mira",
    name: "Mira Quill",
    type: "pc",
    size: "Medium",
    armorClass: 14,
    maxHp: 31,
    speed: "30 ft.",
    initiativeBonus: 3,
    abilityScores: { ...commonScores, dex: 16, int: 15 },
    savingThrows: ["Dex +5", "Int +4"],
    skills: ["Arcana +4", "Investigation +4"],
    senses: "passive Perception 12",
    languages: "Common, Elvish",
    traits: [{ name: "Prepared Spark", description: "Once per round, mark a target after casting a spell." }],
    actions: [{ name: "Bright Bolt", description: "+5 to hit, 1d10 radiant damage." }],
    bonusActions: [{ name: "Arcane Step", description: "Move 10 ft. without provoking from one creature." }],
    notes: "Mobile spellcaster. Player enters initiative manually.",
    tags: ["player", "caster"],
    color: "Teal",
    autoRollEligible: false,
  },
  {
    id: "pc-tovin",
    name: "Tovin Bramble",
    type: "pc",
    size: "Small",
    armorClass: 15,
    maxHp: 36,
    speed: "25 ft.",
    initiativeBonus: 4,
    abilityScores: { ...commonScores, dex: 18, wis: 14 },
    savingThrows: ["Dex +6", "Wis +4"],
    skills: ["Stealth +8", "Perception +6"],
    senses: "passive Perception 16",
    languages: "Common, Halfling",
    traits: [{ name: "Low Profile", description: "Can hide behind Medium or larger allies." }],
    actions: [{ name: "Twin Knives", description: "+6 to hit, 1d4+4 piercing damage twice." }],
    reactions: [{ name: "Slip Aside", description: "Reduce one melee hit by 1d6." }],
    notes: "Skirmisher who likes high initiative.",
    tags: ["player", "skirmisher"],
    color: "Green",
    autoRollEligible: false,
  },
  {
    id: "goblin-cinder",
    name: "Cindercap Sneak",
    type: "enemy",
    size: "Small",
    armorClass: 14,
    maxHp: 11,
    speed: "30 ft.",
    initiativeBonus: 3,
    abilityScores: { ...commonScores, str: 8, dex: 16, cha: 8 },
    skills: ["Stealth +5", "Acrobatics +5"],
    senses: "darkvision 60 ft., passive Perception 10",
    languages: "Common, gutter cant",
    challengeRating: "1/4",
    traits: [{ name: "Smoke Duck", description: "After missing with an attack, the sneak can move 10 ft." }],
    actions: [{ name: "Notched Dagger", description: "+5 to hit, 1d4+3 piercing damage." }],
    tags: ["goblin-style", "ambusher"],
    color: "Red",
    autoRollEligible: true,
  },
  {
    id: "goblin-rattle",
    name: "Rattlebone Slinger",
    type: "enemy",
    size: "Small",
    armorClass: 13,
    maxHp: 9,
    speed: "30 ft.",
    initiativeBonus: 2,
    abilityScores: { ...commonScores, dex: 15, wis: 8 },
    skills: ["Sleight of Hand +4"],
    senses: "darkvision 60 ft., passive Perception 9",
    languages: "Common, gutter cant",
    challengeRating: "1/4",
    traits: [{ name: "Pack Nerve", description: "Has advantage on morale checks while near two allies." }],
    actions: [{ name: "Clatter Sling", description: "+4 to hit, 1d6+2 bludgeoning damage." }],
    bonusActions: [{ name: "Scatter", description: "Disengage after making a ranged attack." }],
    tags: ["goblin-style", "ranged"],
    color: "Red",
    autoRollEligible: true,
  },
  {
    id: "goblin-murk",
    name: "Murkpot Hexer",
    type: "enemy",
    size: "Small",
    armorClass: 12,
    maxHp: 16,
    speed: "30 ft.",
    initiativeBonus: 1,
    abilityScores: { ...commonScores, int: 12, wis: 13, cha: 14 },
    savingThrows: ["Wis +3"],
    skills: ["Deception +4"],
    senses: "darkvision 60 ft., passive Perception 11",
    languages: "Common, gutter cant",
    challengeRating: "1/2",
    traits: [{ name: "Bad Luck Brew", description: "A creature damaged by the hexer loses 1d4 from its next attack roll." }],
    actions: [{ name: "Murk Bolt", description: "+4 to hit, 1d8+2 necrotic damage." }],
    reactions: [{ name: "Spiteful Pop", description: "When hit, deal 2 poison damage to the attacker." }],
    tags: ["goblin-style", "caster"],
    color: "Purple",
    autoRollEligible: true,
  },
  {
    id: "goblin-bristle",
    name: "Bristlejaw Guard",
    type: "enemy",
    size: "Small",
    armorClass: 16,
    maxHp: 18,
    speed: "25 ft.",
    initiativeBonus: 0,
    abilityScores: { ...commonScores, str: 14, con: 13 },
    skills: ["Athletics +4"],
    senses: "darkvision 60 ft., passive Perception 10",
    languages: "Common, gutter cant",
    challengeRating: "1/2",
    traits: [{ name: "Lock Shields", description: "Gains +1 AC while adjacent to another guard." }],
    actions: [{ name: "Hooked Spear", description: "+4 to hit, 1d6+2 piercing damage and pull 5 ft." }],
    tags: ["goblin-style", "guard"],
    color: "Red",
    autoRollEligible: true,
  },
  {
    id: "shadow-hound",
    name: "Duskmaw Hound",
    type: "enemy",
    size: "Medium",
    armorClass: 14,
    maxHp: 37,
    speed: "40 ft.",
    initiativeBonus: 3,
    abilityScores: { ...commonScores, str: 15, dex: 16, con: 14, wis: 12 },
    skills: ["Perception +5", "Stealth +5"],
    senses: "darkvision 90 ft., passive Perception 15",
    languages: "understands Shadow cant",
    challengeRating: "2",
    traits: [{ name: "Dim Pounce", description: "Deals an extra 1d6 damage after moving out of dim light." }],
    actions: [{ name: "Umbral Bite", description: "+5 to hit, 2d6+3 piercing damage." }],
    bonusActions: [{ name: "Fade Low", description: "Hide while in dim light or darkness." }],
    tags: ["shadow", "beast"],
    color: "Indigo",
    autoRollEligible: true,
  },
  {
    id: "boss-velkora",
    name: "Velkora, Lantern Tyrant",
    type: "boss",
    size: "Medium",
    armorClass: 18,
    maxHp: 126,
    speed: "30 ft., hover 20 ft.",
    initiativeBonus: 4,
    abilityScores: { str: 14, dex: 18, con: 16, int: 15, wis: 13, cha: 17 },
    savingThrows: ["Dex +7", "Con +6", "Cha +6"],
    skills: ["Intimidation +6", "Perception +4"],
    senses: "darkvision 120 ft., passive Perception 14",
    languages: "Common, Infernal, gutter cant",
    challengeRating: "6",
    traits: [
      { name: "Lantern Aura", description: "Enemies starting their turn within 10 ft. cannot benefit from being hidden." },
      { name: "Commanding Glare", description: "Once per round, a nearby ally may move 10 ft. after Velkora acts." },
    ],
    actions: [
      { name: "Iron Lantern", description: "+7 to hit, 1d10+4 bludgeoning plus 1d8 fire damage." },
      { name: "Flare Order", description: "Two allies make one weapon attack against marked targets." },
    ],
    reactions: [{ name: "No, You Stay", description: "A creature that leaves reach must pass a Dex save or stop moving." }],
    legendaryActions: [
      { name: "Burning Step", description: "Move up to half speed and leave a 5 ft. burning mark." },
      { name: "Hard Stare", description: "One creature Velkora can see has disadvantage on its next save." },
    ],
    notes: "Boss pressure piece. Use reinforcements when she drops below half HP.",
    tags: ["boss", "commander"],
    color: "Gold",
    autoRollEligible: true,
  },
];

export function createCombatant(
  template: CreatureTemplate,
  copyNumber = 1,
): EncounterCombatant {
  const suffix = template.type === "pc" ? "" : ` ${copyNumber}`;

  return {
    ...template,
    combatantId: `${template.id}-${Date.now()}-${Math.random()
      .toString(36)
      .slice(2, 8)}`,
    templateId: template.id,
    displayName: `${template.name}${suffix}`,
    currentHp: template.maxHp,
    initiative: null,
    manualInitiative: template.type === "pc",
    conditions: [],
  };
}
